linter-settings:
linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
#    - funlen
    - gochecknoinits
#    - gocognit
    - goconst
#    - gocritic
    - gocyclo
    - gofmt
    - goimports
#    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
#    - interfacer
#    - lll
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
#    - scopelint
    - staticcheck
    - structcheck
#    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
#    - whitespace
    - prealloc
    - asciicheck

# do not enable...
#    - gochecknoglobals
#    - godot
#    - godox
#    - goerr113
#    - maligned
#    - nestif
#    - testpackage
#    - wsl

